registration:
  course:
    max: 5
  student:
    max: 50


spring:
  datasource:
    url: jdbc:mysql://school_mysql_db:3306/schoolapp
    username: root
    password: fb1907
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  logging:
    level:
      "liquibase": info
