spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolapp
    username: root
    password: fb1907
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false
  logging:
    level:
      "liquibase": info
